### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by ric96** [Make-Magazine/PirateRadio#23]
[root@alarmpi pirateradio]# Traceback (most recent call last):
  File "PirateRadio.py", line 180, in <module>
    main()
  File "PirateRadio.py", line 36, in main
    files = build_file_list()
  File "PirateRadio.py", line 48, in build_file_list
    for root, folders, files in os.walk(music_dir):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

[root@alarmpi pirateradio]#

**Comment by ric96** [comment]
had an extra "/" in the config file

**Comment by FloridaNetwork** [comment]
thank you

**Comment by ric96** [comment]
Found the actual reason, its not a '/' but rather its a song file with a character not recognized by utf-8 or ascii, in my case it was ü, removing this frim the file name solved the problem.
