### ISSUE TITLE
Raspberry pi 2

### ISSUE THREAD

**Issue by Smarticles101** [Make-Magazine/PirateRadio#24]
Will there ever be support for raspberry pi 2?

**Comment by cdrik6** [comment]
Same question, seems to be so easy for all, and on my side nothing works, and no idea how to fix, except may be a release issue as i use Pi 2 Model B

**Comment by guillermogf** [comment]
This project hasn't been updated in over a year, so if I were you I wouldn't expect that release coming from here.

I recommend you looking to other similar projects that do have support for Pi2. I don't know any, but I think there's probably some.

**Comment by FloridaNetwork** [comment]
Yes there is support on the raspberry PI.

we are just starting again, sorry for the delay.

Hans de Wilde
7272720911

**Comment by Smarticles101** [comment]
This project is dead, Im closing this issue for now
