### ISSUE TITLE
Release source code of pifm.c

### ISSUE THREAD

**Issue by metachris** [Make-Magazine/PirateRadio#4]
Please release the modified version of pifm.c.

**Comment by eyalsch** [comment]
http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

**Comment by metachris** [comment]
The article (http://makezine.com/projects/make-38-cameras-and-av/raspberry-pirate-radio/) explains that you improved the source code. If you made changes it would be nice to publish them again under a GPL compatible license. 

If you haven't made changes it might be nice to add the C source code nevertheless?

**Comment by d4m4s74** [comment]
I just compared the md5s of the one in this git and the one on irobotics, it's exactly the same.

**Comment by zerotri** [comment]
Finally merged d4m4s74's addition of the source code in because I haven't had much time to work on this lately. Going to be closing this. Reopen if necessary.
